/// Flutter icons SliderTestOutlines
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SliderTestOutlines
///      fonts:
///       - asset: fonts/SliderTestOutlines.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SliderTestOutlines {
  SliderTestOutlines._();

  static const _kFontFam = 'SliderTestOutlines';
  static const String? _kFontPkg = null;

  static const IconData slidericon2 = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData slidericon3 =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slidericon4 =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slidericon5 =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slidericon6 =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slidericon7 =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slidericon8 =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slidericon0 =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slidericon1 =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
